=== samuelsuarezramos2006-cpu/SEW/etapa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uniovi.es" xmlns="http://www.uniovi.es" elementFormDefault="qualified">
    <xs:element name="etapa">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre" />
                <xs:element ref="numero" />
                <xs:element ref="longitud" />
                <xs:element ref="fecha" />
                <xs:element ref="tiempo_ganador" />
                <xs:element ref="velocidad_media" />
                <xs:element ref="desnivel" />
                <xs:element ref="ciudad_salida" />
                <xs:element ref="ciudad_llegada" />
                <xs:element ref="tipo" />
                <xs:element ref="referencias" />
                <xs:element ref="galeria_fotografias" />
                <!-- Se añade minOccurs="0" para hacerlos opcionales ya que no aparecen en el XML -->
                <xs:element ref="galeria_videos" minOccurs="0" />
                <xs:element ref="galeria_sonidos" minOccurs="0" />
                <xs:element ref="coordenadas_salida" />
                <xs:element ref="coordenadas_meta" />
                <xs:element ref="hitos" />
                <xs:element ref="clasificacion_etapa" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="nombre" type="xs:string" />
    <xs:element name="numero" type="xs:integer" />
    <xs:element name="longitud">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:float">
                    <xs:attribute name="unidad" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="fecha" type="xs:string" />
    <xs:element name="tiempo_ganador" type="xs:time" />
    <xs:element name="velocidad_media">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:float">
                    <xs:attribute name="unidad" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="desnivel">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="unidad" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="ciudad_salida" type="xs:string" />
    <xs:element name="ciudad_llegada" type="xs:string" />
    <xs:element name="tipo" type="xs:string" />
    <xs:element name="referencias">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="referencia" type="xs:string" />
    <xs:element name="galeria_fotografias">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="fotografia" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="fotografia" type="xs:string" />
    <xs:element name="galeria_videos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="video" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="video" type="xs:string" />
    <xs:element name="galeria_sonidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="sonido" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="sonido" type="xs:string" />
    <xs:element name="coordenadas_salida">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="latitud" />
                <xs:element ref="longitud_geo" />
                <xs:element ref="altitud" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="coordenadas_meta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="latitud" />
                <xs:element ref="longitud_geo" />
                <xs:element ref="altitud" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="latitud">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:float">
                    <xs:attribute name="unidad" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="longitud_geo">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:float">
                    <xs:attribute name="unidad" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="altitud">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:float">
                    <xs:attribute name="unidad" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="hitos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="puerto_montana" />
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="sprint" />
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="punto_anonimo" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="puerto_montana">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre_puerto" />
                <xs:element ref="categoria" />
                <xs:element ref="latitud" />
                <xs:element ref="longitud_geo" />
                <xs:element ref="altitud" />
                <xs:element ref="distancia" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="nombre_puerto" type="xs:string" />
    <xs:element name="categoria" type="xs:string" />
    <xs:element name="sprint">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre_sprint" />
                <xs:element ref="bonificado" />
                <xs:element ref="latitud" />
                <xs:element ref="longitud_geo" />
                <xs:element ref="altitud" />
                <xs:element ref="distancia" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="nombre_sprint" type="xs:string" />
    <xs:element name="bonificado" type="xs:string" />
    <xs:element name="punto_anonimo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="latitud" />
                <xs:element ref="longitud_geo" />
                <xs:element ref="altitud" />
                <xs:element ref="distancia" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="distancia">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:float">
                    <xs:attribute name="unidad" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="clasificacion_etapa">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="ciclista" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="clasificacion_general">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="ciclista" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="clasificacion_equipos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="equipo" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ciclista">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="posicion" />
                <xs:element ref="nombre_ciclista" />
                <xs:element ref="tiempo" />
                <xs:element ref="diferencia" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="equipo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="posicion" />
                <xs:element ref="nombre_equipo" />
                <xs:element ref="tiempo" />
                <xs:element ref="diferencia" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="posicion" type="xs:integer" />
    <xs:element name="nombre_ciclista" type="xs:string" />
    <xs:element name="nombre_equipo" type="xs:string" />
    <xs:element name="tiempo" type="xs:string" />
    <xs:element name="diferencia" type="xs:string" />
</xs:schema>

=== samuelsuarezramos2006-cpu/SEW/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<etapa xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es etapa.xsd">

    <nombre>Monaco - Monaco</nombre>
    <numero>1</numero>
    <longitud unidad="km">9.4</longitud>
    <fecha>22/08/2026</fecha>
    <tiempo_ganador>00:11:45</tiempo_ganador>
    <velocidad_media unidad="km/h">48.0</velocidad_media>
    <desnivel unidad="m">59</desnivel>
    <ciudad_salida>Monaco</ciudad_salida>
    <ciudad_llegada>Monaco</ciudad_llegada>
    <tipo>Contrarreloj Individual</tipo>
    
    <referencias>
        <referencia>"https://www.lavuelta.es/es/"</referencia>
        <referencia>"https://www.marca.com/ciclismo/vuelta-espana/clasificacion/etapa-1.html"</referencia>
        <referencia>"https://www.sport.es/es/noticias/ciclismo/etapa-1-vuelta-espana-2026-perfil-recorrido-horario-contrarreloj-133548651"</referencia>
    </referencias>
    
    <galeria_fotografias>
        <fotografia>multimedia/mapa.jpg.jpg</fotografia>
        <fotografia>multimedia/carrera.jpg</fotografia>
        <fotografia>multimedia/ciclista.jpg</fotografia>
    </galeria_fotografias>
    
    
    <coordenadas_salida>
        <latitud unidad="grados">43.732167</latitud>
        <longitud_geo unidad="grados">7.422222</longitud_geo>
        <altitud unidad="m">48</altitud>
    </coordenadas_salida>
    
    <coordenadas_meta>
        <latitud unidad="grados">43.732167</latitud>
        <longitud_geo unidad="grados">7.422222</longitud_geo>
        <altitud unidad="m">10</altitud>
    </coordenadas_meta>
    
    <hitos>
        <punto_anonimo>
            <latitud unidad="grados">43.731100</latitud>
            <longitud_geo unidad="grados">7.425000</longitud_geo>
            <altitud unidad="m">8</altitud>
            <distancia unidad="km">5.6</distancia>
        </punto_anonimo>
    </hitos>

    <clasificacion_etapa>
        <ciclista>
            <posicion>1</posicion>
            <nombre_ciclista> Tadej Pogačar</nombre_ciclista>
            <tiempo>00:10:57</tiempo>
            <diferencia>00:00:00</diferencia>
        </ciclista>
        <ciclista>
            <posicion>2</posicion>
            <nombre_ciclista> Ethan Hayter</nombre_ciclista>
            <tiempo>00:10:57</tiempo>
            <diferencia>+00:00:00</diferencia>
        </ciclista>
        <ciclista>
            <posicion>3</posicion>
            <nombre_ciclista>Joshua Tarling</nombre_ciclista>
            <tiempo>00:11:01</tiempo>
            <diferencia>+00:00:03:91</diferencia>
        </ciclista>
    </clasificacion_etapa>

</etapa>
